PROJECT = foo
DEPS = tuah sync cowboy erlydtl jsx lager cowlib ranch bson pbkdf2 mongodb 

dep_tuah = git https://github.com/mhishami/tuah.git master
dep_mongodb = git https://github.com/comtihon/mongodb-erlang.git master

include erlang.mk
